### PR TITLE
Data retrieval

### PR DESCRIPTION
**Pull request by OliviaLynn**
## Change Description

- [ ] My PR includes a link to the issue that I am addressing

## Code Quality
- [ ] I have read the Contribution Guide
- [ ] My code follows the code style of this project
- [ ] My code builds (or compiles) cleanly without any errors or warnings
- [ ] My code contains relevant comments and necessary documentation

### Bug Fix Checklist
- [ ] My fix includes a new test that breaks as a result of the bug (if possible)
- [ ] My change includes a breaking change
  - [ ] My change includes backwards compatibility and deprecation warnings (if possible)

### New Feature Checklist
- [ ] I have added or updated the docstrings associated with my feature using the [NumPy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html)
- [ ] I have updated the tutorial to highlight my new feature (if appropriate)
- [ ] I have added unit/End-to-End (E2E) test cases to cover my new feature
- [ ] My change includes a breaking change
  - [ ] My change includes backwards compatibility and deprecation warnings (if possible)

### Documentation Change Checklist
- [ ] Any updated docstrings use the [NumPy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html)

### Build/CI Change Checklist
- [ ] If required or optional dependencies have changed (including version numbers), I have updated the README to reflect this
- [ ] If this is a new CI setup, I have added the associated badge to the README

### Other Change Checklist
- [ ] Any new or updated docstrings use the [NumPy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html).
- [ ] I have updated the tutorial to highlight my new feature (if appropriate)
- [ ] I have added unit/End-to-End (E2E) test cases to cover any changes
- [ ] My change includes a breaking change
  - [ ] My change includes backwards compatibility and deprecation warnings (if possible)

### CODE REVIEW

**Review by drewoldag — APPROVED** [review]
I think that this looks fine for now. I don't think that the STAR_MOD_ALL.list file is being used in the demo notebook. If that's true, then we should remove it, if it is, then we should include it in a reasonable directory next to the notebook. 

As one of the follow up item, to retrieve all the data, if OSF is being troublesome, then perhaps we can use the entire registry file as an input list? (forgive me if you already told me that this was a plan)

**Comment by OliviaLynn** [comment]
> I think that this looks fine for now. I don't think that the STAR_MOD_ALL.list file is being used in the demo notebook. If that's true, then we should remove it, if it is, then we should include it in a reasonable directory next to the notebook.
> 

Yes. I’m not planning on adding STAR_MOD_ALL into the code haphazardly into the repository (we get it along with the rest of the data, if we ask for sed/STAR/, or download it specifically via url), but included it in case we needed it on the fly during our session today to demonstrate local file lists. 

(In candor this draft PR was not intended for review, and as of such I did not add you as a reviewer; I'd rather not waste your time until I'm seeking meaningful feedback on the code at hand. I had imagined the “WIP” in the PR title made this clear--what can I do in the future to advertise the in-progress state of my draft PRs?)


> As one of the follow up item, to retrieve all the data, if OSF is being troublesome, then perhaps we can use the entire registry file as an input list? (forgive me if you already told me that this was a plan)

We can also run git clone on the data repository, or directly curl the endpoint of the "Download repository as zip", such as https://github.com/OliviaLynn/LEPHARE-data/archive/refs/heads/main.zip. Both strike me as less error-prone, though I'm open to further discussion. However, I would consider this topic to be outside the scope of the current PR.

**Comment by OliviaLynn** [comment]
Tagging @raphaelshirley for visibility as well, as I am unable to add you as a reviewer through the sidebar. No pressure to look through, but if you have any comments I'm all ears.

**Comment by johannct** [comment]
> Tagging @raphaelshirley for visibility as well, as I am unable to add you as a reviewer through the sidebar. No pressure to look through, but if you have any comments I'm all ears.

I added him.

**Review by drewoldag — APPROVED** [review]
This all still looks fine to me. Thanks for adding a bunch of tests (and they are so fast too!)

**Pull request merged**
